spring:
  profiles:
    active: local
  cache:
    type: ehcache
  activemq:
    in-memory: true
    pool:
      enabled: false
server:
  port: 9998
  context-path: /api
auth:
  jwt:
    expireSeconds: 3000
    key: xxxxxxxyyyy
  openApi:
    expireSeconds: 600
